version: 0.1.{build}

platform:
  - x86

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  VCPKG_DEFAULT_TRIPLET: x86-windows

cache:
  - c:\tools\vcpkg\installed\ -> .appveyor.yml
  - c:\tools\vcpkg\downloads\
  - c:\projects\dev


image:
  - Visual Studio 2015

skip_tags: true

skip_branch_with_pr: true

build:
  verbosity: detailed

clone_folder: c:\projects\cdt-test

shallow_clone: true

configuration: Release

install:
  - if not exist "c:\projects\dev" (
      mkdir c:\projects\dev
      cd c:\projects\dev
      set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip"
      appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
      7z x ninja.zip -oC:\projects\dev\ninja > nul
    )
  - set PATH=%PATH%;C:\projects\dev\ninja
  - ninja --version
  # Verify CMake
  - cmake --version
  # Setup Clang-cl
  - set PATH=%PATH%;"C:\Program Files\LLVM\bin"
  - clang-cl -v
  - set CC=clang-cl
  - set CXX=clang-cl
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - set CMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang-cl"
  # Update vcpkg
  - cd c:\tools\vcpkg
  - vcpkg integrate install
  - git pull
  - vcpkg update
  # Remove conflicting OpenSSL directories
  - rd /s /q c:\OpenSSL-v11-Win32
  - rd /s /q c:\OpenSSL-v11-Win64
  # Install required libraries
  - vcpkg install curl
  - vcpkg install date
  - vcpkg install eigen3
  - vcpkg install tbb
  - vcpkg install cgal


before_build:
  - cd c:\projects\cdt-test

build_script:
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_MAKE_PROGRAM=c:\projects\dev\ninja\ninja.exe -DVCPKG_TARGET_TRIPLET=x86-windows -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build .

notifications:
  - provider: Email
    to:
      - acgetchell@ucdavis.edu

#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
