language: cpp
sudo: false
dist: bionic
osx_image: xcode11.2

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r-test'
    packages:
      - g++-9
      - linuxbrew-wrapper
      - yasm
  homebrew:
    packages:
      - yasm
    update: true

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
#  - |
#    # Install Linuxbrew
#    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
#      PATH="$HOME/.linuxbrew/bin:$PATH"
#      echo 'export PATH="/home/travis/.linuxbrew/bin:$PATH"' >> ~/.bash_profile
#      yes '' | brew --version
#      export MANPATH="$(brew --prefix)/share/man:$MANPATH"
#      export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
#      (brew update || brew update)
#      brew doctor
#      brew config
#    fi
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg integrate install
  - git pull

install:
  - if [[ "$CXX" == "g++" ]]; then export CXX="g++-9" CC="gcc-9"; fi
  - ./vcpkg install date
  - ./vcpkg install catch2
  - ./vcpkg install eigen3
  - ./vcpkg install boost
  - ./vcpkg install cgal
  - cd ..

script:
  - mkdir build
  - cd build
  - cd build || exit
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build .

after_success:
  - ctest