language: cpp
sudo: false
dist: bionic
osx_image: xcode11.2

addons:
  apt:
    packages:
      - linuxbrew-wrapper
  homebrew:
    packages:
      - yasm
    update: true

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - |
    # Install Linuxbrew
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      PATH="$HOME/.linuxbrew/bin:$PATH"
      echo 'export PATH="/home/travis/.linuxbrew/bin:$PATH"' >> ~/.bash_profile
      yes '' | brew --version
      export MANPATH="$(brew --prefix)/share/man:$MANPATH"
      export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
      (brew update || brew update)
      brew doctor
      brew config
      brew install yasm
    fi
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg integrate install
  - git pull

install:
  - ./vcpkg install date
  - ./vcpkg install catch2
  - ./vcpkg install eigen3
  - ./vcpkg install boost
  - ./vcpkg install cgal
  - cd ..

script:
  - mkdir build
  - cd build
  - cd build || exit
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build .

after_success:
  - ctest