version: ~> 1.0
language: cpp
dist: bionic
osx_image: xcode11.3

cache:
  - ccache
  - directories:
      - $TRAVIS_BUILD_DIR/vcpkg

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - g++-9
      - clang-10
      - ninja-build
      - yasm
  homebrew:
    packages:
      - ccache
      - ninja
      - yasm
    update: true

os:
  - linux
  - osx

compiler:
  - g++-9
  - clang-10

jobs:
  allow_failures:
    - os: osx


before_install:
  - git clone https://github.com/Microsoft/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - ./vcpkg integrate install
  - git pull

install:
  #- if [[ "$CXX" == "g++" ]]; then export CXX="g++-9" CC="gcc-9"; fi
  - ./vcpkg install catch2
  - ./vcpkg install docopt
  - ./vcpkg install fmt
  - ./vcpkg install ms-gsl
  - ./vcpkg install eigen3
  - ./vcpkg install tbb
  - ./vcpkg install cgal
  - ./vcpkg upgrade --no-dry-run
  - ./vcpkg list
  - rm -rf downloads buildtrees packages
  - cd ..
  - pwd

script:
  - mkdir build
  - cd build || exit
  - pwd
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$TRAVIS_BUILD_DIR/vcpkg/scripts/buildsystems/vcpkg.cmake ..
  - cmake --build .

after_success:
  - ctest
